"""Basketball vocabulary used by the simple keyword parser.

The values are intentionally close to words that appear in NBA play
descriptions because these terms are also used for local text filters.
"""

# NBA Stats context measures. These decide what VideoDetailsAsset should fetch.
CONTEXT_KEYWORDS = {
    # Made/scoring plays
    "score": "PTS",
    "scores": "PTS",
    "scored": "PTS",
    "scoring": "PTS",
    "point": "PTS",
    "points": "PTS",
    "bucket": "PTS",
    "buckets": "PTS",
    "basket": "PTS",
    "baskets": "PTS",
    "fgm": "PTS",
    "make": "PTS",
    "makes": "PTS",
    "made": "PTS",
    "hit": "PTS",
    "hits": "PTS",
    "drain": "PTS",
    "drains": "PTS",
    "finish": "PTS",
    "finishes": "PTS",
    # Field-goal attempts, usually filtered locally for misses
    "attempt": "FGA",
    "attempts": "FGA",
    "fga": "FGA",
    "miss": "FGA",
    "misses": "FGA",
    "missed": "FGA",
    "brick": "FGA",
    "bricks": "FGA",
    "airball": "FGA",
    "airballs": "FGA",
    # Assists
    "assist": "AST",
    "assists": "AST",
    "ast": "AST",
    "dime": "AST",
    "dimes": "AST",
    "pass": "AST",
    "passes": "AST",
    "feed": "AST",
    "feeds": "AST",
    # Rebounds
    "rebound": "REB",
    "rebounds": "REB",
    "reb": "REB",
    "board": "REB",
    "boards": "REB",
    "glass": "REB",
    # Steals
    "steal": "STL",
    "steals": "STL",
    "stl": "STL",
    "pick": "STL",
    "picks": "STL",
    "interception": "STL",
    "interceptions": "STL",
    # Blocks
    "block": "BLK",
    "blocks": "BLK",
    "blocked": "BLK",
    "blk": "BLK",
    "swat": "BLK",
    "swats": "BLK",
    "swatted": "BLK",
    "rejection": "BLK",
    "rejections": "BLK",
    # Turnovers
    "turnover": "TOV",
    "turnovers": "TOV",
    "tov": "TOV",
    "giveaway": "TOV",
    "giveaways": "TOV",
    "lost": "TOV",
}


# Single-token words that can be matched against NBA play descriptions.
SHOT_KEYWORDS = {
    # Rim attempts
    "dunk": "DUNK",
    "dunks": "DUNK",
    "dunked": "DUNK",
    "slam": "DUNK",
    "slams": "DUNK",
    "jam": "DUNK",
    "jams": "DUNK",
    "layup": "LAYUP",
    "layups": "LAYUP",
    "fingerroll": "FINGER ROLL",
    "tip": "TIP",
    "tips": "TIP",
    "putback": "PUTBACK",
    "putbacks": "PUTBACK",
    # Jump shots
    "jumper": "JUMP SHOT",
    "jumpers": "JUMP SHOT",
    "j": "JUMP SHOT",
    "three": "3PT",
    "threes": "3PT",
    "triple": "3PT",
    "triples": "3PT",
    "3": "3PT",
    "3pt": "3PT",
    "trey": "3PT",
    "treys": "3PT",
    "midrange": "JUMP SHOT",
    "middy": "JUMP SHOT",
    "fadeaway": "FADEAWAY",
    "fadeaways": "FADEAWAY",
    "hook": "HOOK",
    "hooks": "HOOK",
    "floater": "FLOATING",
    "floaters": "FLOATING",
    "runner": "RUNNING",
    "runners": "RUNNING",
    "bank": "BANK",
    "banks": "BANK",
    # Movement/style descriptors
    "driving": "DRIVING",
    "drive": "DRIVING",
    "drives": "DRIVING",
    "cutting": "CUTTING",
    "cut": "CUTTING",
    "cuts": "CUTTING",
    "running": "RUNNING",
    "transition": "RUNNING",
    "pullup": "PULLUP",
    "stepback": "STEP BACK",
    "turnaround": "TURNAROUND",
    "reverse": "REVERSE",
    "alleyoop": "ALLEY OOP",
    "oop": "ALLEY OOP",
}


# Multi-token phrases. Keys should be normalized lowercase text.
PHRASE_KEYWORDS = {
    "three pointer": "3PT",
    "three pointers": "3PT",
    "3 pointer": "3PT",
    "3 pointers": "3PT",
    "three point": "3PT",
    "3 point": "3PT",
    "jump shot": "JUMP SHOT",
    "jump shots": "JUMP SHOT",
    "pull up": "PULLUP",
    "pull-up": "PULLUP",
    "pullup jumper": "PULLUP",
    "step back": "STEP BACK",
    "step-back": "STEP BACK",
    "step back three": "STEP BACK|3PT",
    "step-back three": "STEP BACK|3PT",
    "fade away": "FADEAWAY",
    "fade-away": "FADEAWAY",
    "hook shot": "HOOK",
    "hook shots": "HOOK",
    "floating jump shot": "FLOATING",
    "finger roll": "FINGER ROLL",
    "finger-roll": "FINGER ROLL",
    "bank shot": "BANK",
    "bank shots": "BANK",
    "tip shot": "TIP",
    "tip shots": "TIP",
    "tip in": "TIP",
    "tip-in": "TIP",
    "put back": "PUTBACK",
    "put-back": "PUTBACK",
    "alley oop": "ALLEY OOP",
    "alley-oop": "ALLEY OOP",
    "alley oop dunk": "ALLEY OOP|DUNK",
    "alley-oop dunk": "ALLEY OOP|DUNK",
    "driving dunk": "DRIVING|DUNK",
    "driving layup": "DRIVING|LAYUP",
    "cutting dunk": "CUTTING|DUNK",
    "running dunk": "RUNNING|DUNK",
    "running layup": "RUNNING|LAYUP",
    "reverse layup": "REVERSE|LAYUP",
    "reverse dunk": "REVERSE|DUNK",
    "turnaround jumper": "TURNAROUND|JUMP SHOT",
    "turnaround jump shot": "TURNAROUND|JUMP SHOT",
}


MISS_KEYWORDS = {
    "miss",
    "misses",
    "missed",
    "brick",
    "bricks",
    "airball",
    "airballs",
}


# These are not used for endpoint params yet, but keeping them explicit makes
# the next parser pass easier.
TIME_CONTEXT_KEYWORDS = {
    "clutch",
    "late",
    "buzzer",
    "buzzerbeater",
    "buzzer-beater",
    "gamewinner",
    "game-winner",
}


SCORE_CONTEXT_KEYWORDS = {
    "tying",
    "tie",
    "lead",
    "leading",
    "goahead",
    "go-ahead",
}


SEASON_TYPE_KEYWORDS = {
    "playoff": "Playoffs",
    "playoffs": "Playoffs",
    "postseason": "Playoffs",
    "regular": "Regular Season",
    "season": "Regular Season",
    "regular season": "Regular Season",
}


# NBA Stats uses season-month buckets for the Month parameter:
# 0 = all months, 1 = October, 2 = November, etc.
MONTH_KEYWORDS = {
    "october": 1,
    "oct": 1,
    "november": 2,
    "nov": 2,
    "december": 3,
    "dec": 3,
    "january": 4,
    "jan": 4,
    "february": 5,
    "feb": 5,
    "march": 6,
    "mar": 6,
    "april": 7,
    "apr": 7,
    "may": 8,
    "june": 9,
    "jun": 9,
    "july": 10,
    "jul": 10,
}


PERIOD_KEYWORDS = {
    "q1": 1,
    "1q": 1,
    "first": 1,
    "first quarter": 1,
    "1st": 1,
    "1st quarter": 1,
    "q2": 2,
    "2q": 2,
    "second": 2,
    "second quarter": 2,
    "2nd": 2,
    "2nd quarter": 2,
    "q3": 3,
    "3q": 3,
    "third": 3,
    "third quarter": 3,
    "3rd": 3,
    "3rd quarter": 3,
    "q4": 4,
    "4q": 4,
    "fourth": 4,
    "fourth quarter": 4,
    "4th": 4,
    "4th quarter": 4,
    "ot": 5,
    "overtime": 5,
    "first overtime": 5,
    "double overtime": 6,
    "2ot": 6,
    "second overtime": 6,
    "triple overtime": 7,
    "3ot": 7,
    "third overtime": 7,
}
