"""Explicit shorthand that nba_api's official names do not cover.

Full player names and official team names come from nba_api. This file is for
fan shorthand, nicknames, and common spellings we want to support directly.
"""

TEAM_ALIASES = {
    "okc": "Oklahoma City Thunder",
    "gsw": "Golden State Warriors",
    "dubs": "Golden State Warriors",
    "la lakers": "Los Angeles Lakers",
    "la clippers": "Los Angeles Clippers",
    "clips": "Los Angeles Clippers",
    "sixers": "Philadelphia 76ers",
    "wolves": "Minnesota Timberwolves",
    "t-wolves": "Minnesota Timberwolves",
    "t wolves": "Minnesota Timberwolves",
    "twolves": "Minnesota Timberwolves",
    "mavs": "Dallas Mavericks",
    "blazers": "Portland Trail Blazers",
    "cavs": "Cleveland Cavaliers",
}


PLAYER_ALIASES = {
    "ad": "Anthony Davis",
    "bam": "Bam Adebayo",
    "book": "Devin Booker",
    "bron": "LeBron James",
    "cade": "Cade Cunningham",
    "cason": "Cason Wallace",
    "chet": "Chet Holmgren",
    "king james": "LeBron James",
    "lebron": "LeBron James",
    "dame": "Damian Lillard",
    "darius": "Darius Garland",
    "deaaron": "De'Aaron Fox",
    "deebo": "DeMar DeRozan",
    "demar": "DeMar DeRozan",
    "donovan": "Donovan Mitchell",
    "donovan mitchel": "Donovan Mitchell",
    "fox": "De'Aaron Fox",
    "garland": "Darius Garland",
    "hali": "Tyrese Haliburton",
    "haliburton": "Tyrese Haliburton",
    "ja": "Ja Morant",
    "jamal": "Jamal Murray",
    "jb": "Jalen Brunson",
    "jimmy": "Jimmy Butler",
    "jimmy buckets": "Jimmy Butler",
    "jokic": "Nikola Jokic",
    "joker": "Nikola Jokic",
    "jrue": "Jrue Holiday",
    "julius": "Julius Randle",
    "kawhi": "Kawhi Leonard",
    "klaw": "Kawhi Leonard",
    "kyrie": "Kyrie Irving",
    "lamelo": "LaMelo Ball",
    "lauri": "Lauri Markkanen",
    "lillard": "Damian Lillard",
    "luka": "Luka Doncic",
    "markkanen": "Lauri Markkanen",
    "mitchell": "Donovan Mitchell",
    "morant": "Ja Morant",
    "paolo": "Paolo Banchero",
    "pg": "Paul George",
    "pg13": "Paul George",
    "randle": "Julius Randle",
    "sabonis": "Domantas Sabonis",
    "shai": "Shai Gilgeous-Alexander",
    "sga": "Shai Gilgeous-Alexander",
    "spida": "Donovan Mitchell",
    "steph": "Stephen Curry",
    "chef curry": "Stephen Curry",
    "curry": "Stephen Curry",
    "kd": "Kevin Durant",
    "durant": "Kevin Durant",
    "embiid": "Joel Embiid",
    "joel": "Joel Embiid",
    "the process": "Joel Embiid",
    "giannis": "Giannis Antetokounmpo",
    "greek freak": "Giannis Antetokounmpo",
    "wemby": "Victor Wembanyama",
    "wembanyama": "Victor Wembanyama",
    "harden": "James Harden",
    "ant": "Anthony Edwards",
    "ant man": "Anthony Edwards",
    "ar15": "Austin Reaves",
    "reaves": "Austin Reaves",
    "trae": "Trae Young",
    "ice trae": "Trae Young",
    "tatum": "Jayson Tatum",
    "jt": "Jayson Tatum",
    "jayson": "Jayson Tatum",
    "jaylen": "Jaylen Brown",
    "jbrown": "Jaylen Brown",
    "zion": "Zion Williamson",
    "brunson": "Jalen Brunson",
    "coby": "Coby White",
    "cooper": "Cooper Flagg",
    "flagg": "Cooper Flagg",
    "dbook": "Devin Booker",
    "franz": "Franz Wagner",
    "herro": "Tyler Herro",
    "jdub": "Jalen Williams",
    "j-dub": "Jalen Williams",
    "jwill": "Jaylin Williams",
    "j will": "Jaylin Williams",
    "karl": "Karl-Anthony Towns",
    "kat": "Karl-Anthony Towns",
    "keldon": "Keldon Johnson",
    "keegan": "Keegan Murray",
    "kp": "Kristaps Porzingis",
    "kristaps": "Kristaps Porzingis",
    "maxey": "Tyrese Maxey",
    "mikal": "Mikal Bridges",
    "mobley": "Evan Mobley",
    "porzingis": "Kristaps Porzingis",
    "quickley": "Immanuel Quickley",
    "iq": "Immanuel Quickley",
    "rj": "RJ Barrett",
    "scoot": "Scoot Henderson",
    "scottie": "Scottie Barnes",
    "siakam": "Pascal Siakam",
    "pascal": "Pascal Siakam",
    "tyrese": "Tyrese Haliburton",
    "vassell": "Devin Vassell",
    "wiggins": "Andrew Wiggins",
    "zach": "Zach LaVine",
    "lavine": "Zach LaVine",
}
